# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Install_python_packages'
    jobs:
    - job: install
      pool:
       vmImage: 'ubuntu-latest'
      steps:     
      - task: CmdLine@2
        inputs:
          script: 'python -m pip install --upgrade pip && pip install -r requirements.txt'

  - stage: 'BlackDuck_Code_Scan'
    jobs:
    - job: detect
      pool:
       vmImage: 'ubuntu-latest'
      steps:
      - task: CmdLine@2
        inputs:
          script: 'python -m pip install --upgrade pip && pip install -r requirements.txt'
      - task: SynopsysDetectTask@9
        inputs:
          BlackDuckService: 'BlackDuck'
          DetectArguments: |
            --detect.project.name=Python-Sample-Application-Python-package-CI
            --detect.project.version.name=Yaml  
            --blackduck.trust.cert=true  
            --detect.detector.search.depth=100  
            --detect.tools=DETECTOR  
            --detect.detector.search.continue=true
            --detect.code.location.name=pipeline-name
          DetectVersion: 'latest'